export const siteConfig = {
  company: {
    name: 'PT Nikawa Teknika Indonesia',
    shortName: 'NTI',
    tagline: 'Distribusi & Solusi Manufaktur Elektronik, Plastik, dan Komponen Industri sejak 2014',
    philosophy: 'Membangun dengan Presisi, Berkarya dengan Inovasi',
    established: '13 Agustus 2014',
    description: 'NTI adalah perusahaan distribusi resin plastik, produk injection molding, GSM modem, komponen elektronik, PCBA, dan berbagai solusi manufaktur sejak 2014.',
  },
  hero: {
    eyebrow: 'Selamat Datang di PT Nikawa Teknika Indonesia',
    title: 'Membangun Solusi Industri, Menguatkan Pertumbuhan',
    subtitle: 'Partner manufaktur elektronik dan plastik terpercaya di Asia Tenggara',
    description: 'Distribusi & Solusi Manufaktur Elektronik, Plastik, dan Komponen Industri sejak 2014',
    ctaPrimary: 'Pelajari Lebih Lanjut',
    ctaSecondary: 'Hubungi Kami',
  },
  values: [
    {
      title: 'Profesional',
      description: 'Standar tinggi dalam setiap layanan dan produk',
      icon: 'professional',
    },
    {
      title: 'Presisi',
      description: 'Akurasi dan ketelitian dalam setiap detail',
      icon: 'precision',
    },
    {
      title: 'Terpercaya',
      description: 'Kepercayaan jangka panjang dengan klien dan partner',
      icon: 'trust',
    },
    {
      title: 'Inovatif',
      description: 'Terus berkembang dengan teknologi terbaru',
      icon: 'innovation',
    },
  ],
  coreValues: [
    'Kepercayaan',
    'Presisi',
    'Pertumbuhan Berkelanjutan',
    'Kolaborasi',
    'Efisiensi',
  ],
  products: [
    {
      id: 'plastic-injection',
      name: 'Plastic Injection Products',
      description: 'Produk hasil injection molding dari berbagai jenis plastik',
      category: 'Manufacturing',
      image: '/images/products/plastic-injection.jpg',
      detail: {
        overview: 'Kami menyediakan jasa injection molding dengan presisi tinggi untuk berbagai kebutuhan industri. Menggunakan teknologi terkini dan material berkualitas, kami menghasilkan produk plastik custom sesuai spesifikasi Anda dengan standar kualitas internasional.',
        features: [
          'Presisi tinggi dengan toleransi ±0.02mm',
          'Kapasitas produksi 10.000 - 1.000.000 unit/bulan',
          'Material: PP, PE, ABS, PC, PVC, Nylon, dll',
          'Standar kualitas ISO 9001:2015',
          'Mold design & engineering support',
          'Post-processing: painting, assembly, packaging',
        ],
        specifications: [
          { label: 'Material', value: 'PP, PE, ABS, PC, PVC, Nylon, POM, dll' },
          { label: 'Toleransi', value: '±0.02mm - ±0.1mm' },
          { label: 'Kapasitas Produksi', value: '10K - 1M unit/bulan' },
          { label: 'Lead Time', value: '3-5 minggu (massal), 1-2 minggu (prototype)' },
          { label: 'Standar Kualitas', value: 'ISO 9001:2015, IPC-A-610 Class 2/3' },
          { label: 'Mold Life', value: '100K - 1M shots' },
        ],
        applications: [
          'Komponen elektronik & elektrikal',
          'Automotive parts',
          'Medical devices',
          'Consumer products',
          'Industrial components',
          'Packaging solutions',
        ],
        benefits: [
          'Cost-effective untuk produksi massal',
          'Konsistensi kualitas tinggi',
          'Fleksibilitas desain',
          'Fast turnaround time',
          'Expert engineering support',
        ],
      },
    },
    {
      id: 'gsm-modem',
      name: 'GSM Modem',
      description: 'Solusi modem untuk sistem industri, komunikasi, dan aplikasi IoT',
      category: 'Electronics',
      image: '/images/products/gsm-modem.jpg',
      detail: {
        overview: 'GSM Modem berkualitas tinggi untuk aplikasi industri, IoT, dan komunikasi data. Mendukung 2G/3G/4G dengan fitur lengkap untuk remote monitoring, data logging, dan sistem kontrol otomatis.',
        features: [
          'Dual-band GSM/GPRS/EDGE, 3G, 4G LTE',
          'AT Command interface',
          'TCP/IP stack built-in',
          'SMS & Voice support',
          'Low power consumption',
          'Industrial temperature range (-40°C to +85°C)',
          'Antenna connector & SIM card slot',
        ],
        specifications: [
          { label: 'Frequency Bands', value: 'GSM 900/1800MHz, 3G 2100MHz, 4G LTE' },
          { label: 'Data Rate', value: 'Up to 150Mbps (4G), 236.8kbps (GPRS)' },
          { label: 'Interface', value: 'UART, USB, SPI, I2C' },
          { label: 'Power Supply', value: '3.3V - 5V DC' },
          { label: 'Operating Temp', value: '-40°C to +85°C' },
          { label: 'Certification', value: 'CE, FCC, RoHS' },
        ],
        applications: [
          'IoT & Smart devices',
          'Remote monitoring systems',
          'Telemetry & data logging',
          'M2M communication',
          'GPS tracking systems',
          'Industrial automation',
        ],
        benefits: [
          'Reliable connectivity',
          'Easy integration',
          'Cost-effective solution',
          'Wide coverage area',
          'Long-term support',
        ],
      },
    },
    {
      id: 'electronic-components',
      name: 'Electronic Components',
      description: 'IC, LED, kapasitor, resistor, elektrolit kapasitor, dan komponen elektronik lainnya',
      category: 'Electronics',
      image: '/images/products/electronic-components.jpg',
      detail: {
        overview: 'Distributor resmi komponen elektronik berkualitas tinggi dari berbagai brand ternama. Ready stock untuk kebutuhan produksi dan prototyping dengan harga kompetitif dan dukungan teknis lengkap.',
        features: [
          'Brand terpercaya: STMicro, TI, Infineon, ON Semi, dll',
          'Ready stock di gudang Jababeka',
          'Minimum order quantity fleksibel',
          'Technical support & datasheet',
          'Quality assurance & traceability',
          'Competitive pricing',
        ],
        specifications: [
          { label: 'Kategori', value: 'IC, LED, Capacitor, Resistor, Transistor, Diode, dll' },
          { label: 'Brand', value: 'STMicro, TI, Infineon, ON Semi, Vishay, Yageo, dll' },
          { label: 'Stock Status', value: 'Ready stock di gudang Jababeka' },
          { label: 'MOQ', value: 'Fleksibel (mulai dari 1 pcs untuk prototyping)' },
          { label: 'Lead Time', value: 'Same day untuk stock, 2-4 minggu untuk PO' },
          { label: 'Quality', value: 'Original & authentic, dengan certificate' },
        ],
        applications: [
          'PCB assembly & prototyping',
          'Industrial electronics',
          'Consumer electronics',
          'Automotive electronics',
          'Medical devices',
          'Power supplies & converters',
        ],
        benefits: [
          'Original & authentic components',
          'Fast delivery',
          'Competitive pricing',
          'Technical expertise',
          'Reliable supply chain',
        ],
      },
    },
    {
      id: 'plastic-resin',
      name: 'Plastic Resin',
      description: 'PP, PE, PC, PVC, ABS Resins for Industry',
      category: 'Materials',
      image: '/images/products/plastic-resin.jpg',
      detail: {
        overview: 'Distributor resin plastik berkualitas tinggi untuk berbagai aplikasi industri. Material dari supplier terpercaya dengan sertifikasi dan dokumentasi lengkap untuk kebutuhan injection molding, extrusion, dan manufacturing.',
        features: [
          'Grade lengkap: PP, PE, PC, PVC, ABS, PS, PA, dll',
          'Virgin & recycled material',
          'Food grade & medical grade available',
          'Color masterbatch & additives',
          'Technical datasheet & MSDS',
          'Bulk & retail packaging',
        ],
        specifications: [
          { label: 'Material Types', value: 'PP, PE, PC, PVC, ABS, PS, PA, POM, PBT, dll' },
          { label: 'Grade', value: 'Virgin, Recycled, Food Grade, Medical Grade' },
          { label: 'Form', value: 'Pellet, Powder, Sheet, Rod' },
          { label: 'Packaging', value: '25kg bag, 1 ton jumbo bag, custom' },
          { label: 'MOQ', value: '1 ton (bulk), 25kg (retail)' },
          { label: 'Storage', value: 'Dry, cool, away from direct sunlight' },
        ],
        applications: [
          'Injection molding',
          'Extrusion & blow molding',
          'Packaging industry',
          'Automotive parts',
          'Consumer products',
          'Medical devices',
        ],
        benefits: [
          'Quality guaranteed',
          'Competitive pricing',
          'Fast delivery',
          'Technical support',
          'Flexible MOQ',
        ],
      },
    },
    {
      id: 'pcba',
      name: 'PCBA',
      description: 'Jasa perakitan PCB sesuai permintaan industri',
      category: 'Manufacturing',
      image: '/images/products/pcba.jpg',
      detail: {
        overview: 'Jasa perakitan PCB (Printed Circuit Board Assembly) profesional dengan standar IPC-A-610 Class 2/3. Partner EMS di Jababeka dengan 4 line SMT high-speed untuk prototype hingga produksi massal.',
        features: [
          '4 line SMT high-speed assembly',
          'IPC-A-610 Class 2 (Class 3 untuk medis/automotive)',
          'Prototype: 3-7 hari kerja',
          'Mass production: 3-5 minggu',
          'Component sourcing & procurement',
          'Testing & quality control',
          'Box build & final assembly',
        ],
        specifications: [
          { label: 'SMT Lines', value: '4 line high-speed SMT' },
          { label: 'Standard', value: 'IPC-A-610 Class 2 (Class 3 available)' },
          { label: 'PCB Size', value: 'Up to 330mm x 250mm' },
          { label: 'Component Types', value: 'SMD, Through-hole, BGA, QFN, dll' },
          { label: 'Prototype Lead Time', value: '3-7 hari kerja' },
          { label: 'Mass Production', value: '3-5 minggu (tergantung volume)' },
        ],
        applications: [
          'Industrial electronics',
          'Medical devices',
          'Automotive electronics',
          'Consumer electronics',
          'IoT devices',
          'Power electronics',
        ],
        benefits: [
          'High quality standard',
          'Fast turnaround',
          'Cost-effective',
          'One-stop service',
          'Expert engineering support',
        ],
      },
    },
    {
      id: 'led-road-stud',
      name: 'LED Road Stud',
      description: 'Solusi pencahayaan jalan dengan teknologi LED',
      category: 'Infrastructure',
      image: '/images/products/led-road-stud.jpg',
      detail: {
        overview: 'LED Road Stud dengan teknologi canggih untuk meningkatkan keselamatan jalan raya. Tahan cuaca ekstrem, hemat energi, dan tahan lama dengan berbagai mode operasi untuk aplikasi jalan tol, bandara, dan area publik.',
        features: [
          'High brightness LED (IP65/IP67)',
          'Solar powered & grid powered options',
          'Auto dimming & motion detection',
          'Weather resistant (IP65/IP67)',
          'Long lifespan (50,000+ hours)',
          'Easy installation & maintenance',
        ],
        specifications: [
          { label: 'Power', value: 'Solar / Grid 12V/24V DC' },
          { label: 'Brightness', value: '100-500 lumens (adjustable)' },
          { label: 'IP Rating', value: 'IP65/IP67' },
          { label: 'Operating Temp', value: '-30°C to +70°C' },
          { label: 'Lifespan', value: '50,000+ hours' },
          { label: 'Material', value: 'Aluminum housing, PC lens' },
        ],
        applications: [
          'Highway & toll roads',
          'Airport runways',
          'Parking lots',
          'Pedestrian crossings',
          'Traffic guidance',
          'Safety zones',
        ],
        benefits: [
          'Energy efficient',
          'Low maintenance',
          'Enhanced safety',
          'Weather resistant',
          'Long lifespan',
        ],
      },
    },
    {
      id: 'smart-water-meter',
      name: 'Smart Water Meter',
      description: 'Sistem meter air pintar dengan teknologi IoT',
      category: 'Infrastructure',
      image: '/images/products/smart-water-meter.jpg',
      detail: {
        overview: 'Smart Water Meter dengan teknologi IoT untuk monitoring konsumsi air real-time. Sistem AMR (Automatic Meter Reading) dengan komunikasi wireless untuk efisiensi operasional dan manajemen sumber daya air yang lebih baik.',
        features: [
          'IoT connectivity (LoRa, NB-IoT, 4G)',
          'Real-time data monitoring',
          'Remote reading & control',
          'Leak detection & alerts',
          'Battery powered (10+ years)',
          'Web dashboard & mobile app',
        ],
        specifications: [
          { label: 'Communication', value: 'LoRa, NB-IoT, 4G, GSM' },
          { label: 'Accuracy', value: 'Class B / Class C (MID certified)' },
          { label: 'Flow Range', value: 'Q1.5 - Q6 (residential), Q6 - Q25 (commercial)' },
          { label: 'Power', value: 'Battery (10+ years) / Mains powered' },
          { label: 'Data Interval', value: 'Configurable (hourly/daily/monthly)' },
          { label: 'IP Rating', value: 'IP68' },
        ],
        applications: [
          'Residential water metering',
          'Commercial buildings',
          'Industrial water management',
          'Municipal water utilities',
          'Water distribution networks',
          'Leak detection systems',
        ],
        benefits: [
          'Accurate measurement',
          'Remote monitoring',
          'Leak detection',
          'Reduced operational cost',
          'Better water management',
        ],
      },
    },
    {
      id: 'fo-gas-meter',
      name: 'FO Gas Meter',
      description: 'Meter gas dengan teknologi fiber optic',
      category: 'Infrastructure',
      image: '/images/products/fo-gas-meter.jpg',
      detail: {
        overview: 'Fiber Optic Gas Meter dengan teknologi canggih untuk pengukuran gas yang akurat dan aman. Menggunakan prinsip interferometri fiber optic untuk deteksi yang sensitif dan tahan terhadap interferensi elektromagnetik.',
        features: [
          'Fiber optic sensing technology',
          'High accuracy & sensitivity',
          'EMI resistant',
          'Explosion-proof design',
          'Remote monitoring capability',
          'Long-term stability',
        ],
        specifications: [
          { label: 'Technology', value: 'Fiber Optic Interferometry' },
          { label: 'Accuracy', value: '±1% (Class 1.0/1.5)' },
          { label: 'Flow Range', value: 'Qmin - Qmax (configurable)' },
          { label: 'Operating Pressure', value: 'Up to 4 bar (standard)' },
          { label: 'Temperature Range', value: '-10°C to +60°C' },
          { label: 'Safety', value: 'ATEX Zone 1/2 certified' },
        ],
        applications: [
          'Natural gas distribution',
          'Industrial gas monitoring',
          'CNG/LPG metering',
          'Gas pipeline networks',
          'Safety monitoring systems',
          'Process control',
        ],
        benefits: [
          'High accuracy',
          'EMI resistant',
          'Safe operation',
          'Long-term reliability',
          'Remote monitoring',
        ],
      },
    },
    {
      id: 'fiber-optic',
      name: 'Fiber Optic',
      description: 'Solusi komunikasi fiber optic untuk industri',
      category: 'Electronics',
      image: '/images/products/fiber-optic.jpg',
      detail: {
        overview: 'Solusi komunikasi fiber optic lengkap untuk aplikasi industri, data center, dan telekomunikasi. Kabel fiber optic, connector, splice, dan peralatan instalasi dengan kualitas tinggi untuk performa optimal.',
        features: [
          'Single mode & multimode fiber',
          'Various connector types (LC, SC, ST, FC)',
          'Fiber optic cables & patch cords',
          'Splice equipment & tools',
          'Testing & measurement equipment',
          'Installation services',
        ],
        specifications: [
          { label: 'Fiber Types', value: 'SMF (G.652), MMF (OM1/OM2/OM3/OM4/OM5)' },
          { label: 'Connectors', value: 'LC, SC, ST, FC, MTP/MPO' },
          { label: 'Cable Types', value: 'Indoor, Outdoor, Armored, Aerial' },
          { label: 'Wavelength', value: '850nm, 1310nm, 1550nm' },
          { label: 'Bandwidth', value: 'Up to 100Gbps (tergantung grade)' },
          { label: 'Standards', value: 'ITU-T, IEC, TIA/EIA' },
        ],
        applications: [
          'Data center connectivity',
          'Telecommunications',
          'Industrial networks',
          'CCTV systems',
          'Broadband networks',
          'Fiber to the home (FTTH)',
        ],
        benefits: [
          'High bandwidth',
          'Low latency',
          'EMI immune',
          'Long distance transmission',
          'Future-proof technology',
        ],
      },
    },
  ],
  partners: [
    {
      name: 'PT. Len Industri',
      logo: '/images/partners/len.png',
    },
    {
      name: 'Hitachi',
      logo: '/images/partners/hitachi.png',
    },
    {
      name: 'WBS Inti',
      logo: '/images/partners/inti.png',
    },
    {
      name: 'Acumen Engineering',
      logo: '/images/partners/acumen.png',
    },
    {
      name: 'Itron',
      logo: '/images/partners/itron.png',
    },
    {
      name: 'FED',
      logo: '/images/partners/fed.png',
    },
    {
      name: 'Telkom Everynet',
      logo: '/images/partners/everynet.png',
    },
    {
      name: 'PT. Citra Sanxing Indonesia',
      logo: '/images/partners/sanxing.png',
    },
    {
      name: 'PT. Hexing Technology',
      logo: '/images/partners/hexing.png',
    },
    {
      name: 'Chemicon',
      logo: '/images/partners/chemicon.png',
    },
  ],
  testimonials: [
    {
      id: 1,
      quote: '(Konten menyusul)',
      author: 'Klien NTI',
      company: 'Perusahaan Partner',
      project: 'Proyek Kolaborasi',
    },
    {
      id: 2,
      quote: '(Konten menyusul)',
      author: 'Klien NTI',
      company: 'Perusahaan Partner',
      project: 'Proyek Kolaborasi',
    },
  ],
  downloads: [
    {
      id: 1,
      title: 'Company Profile',
      description: 'Profil lengkap perusahaan PT Nikawa Teknika Indonesia',
      type: 'PDF',
      size: '2.5 MB',
      url: '/downloads/company-profile.pdf',
    },
  ],
  contact: {
    address: {
      full: 'PBC, Jl. Antilop Raya Pintu 11, Jababeka II Blok E-3, Kel. Jaya Mukti, Kec. Cikarang Pusat, Bekasi 17530, Jawa Barat, Indonesia',
      street: 'Jl. Antilop Raya Pintu 11',
      building: 'Jababeka II Blok E-3',
      city: 'Bekasi 17530',
      province: 'Jawa Barat',
      country: 'Indonesia',
    },
    email: 'cs@nikawa-indonesia.com',
    phone: '+62 21 2945 3728',
    whatsapp: '+62 21 2945 3728',
    hours: 'Senin - Sabtu: 10.00 - 20.00',
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3965.1234567890!2d107.1488!3d-6.3055!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNsKwMTgnMTkuOCJTIDEwN8KwMDgnNTUuNyJF!5e0!3m2!1sen!2sid!4v1234567890123!5m2!1sen!2sid',
    coordinates: {
      lat: -6.3055,
      lng: 107.1488,
    },
    googleMapsUrl: 'https://www.google.com/maps?q=-6.3055,107.1488',
  },
  about: {
    hero: {
      tagline: 'Membangun dengan Presisi, Berkarya dengan Inovasi',
      image: '/images/about/hero.png',
    },
    profile: {
      title: 'Selamat Datang di PT Nikawa Teknika Indonesia',
      content: 'PT Nikawa Teknika Indonesia didirikan pada tanggal 13 Agustus 2014 dan berlokasi di Kawasan Industri Jababeka II, Cikarang, Bekasi. Perusahaan bergerak di bidang distribusi dan penyediaan berbagai komponen elektronik serta produk plastik untuk kebutuhan industri. Dengan operasional yang berbasis di kawasan industri strategis, PT Nikawa Teknika Indonesia mampu melayani berbagai sektor manufaktur dan teknologi yang membutuhkan produk berkualitas tinggi serta layanan yang handal.',
    },
    identity: {
      name: 'PT. Nikawa Teknika Indonesia',
      established: '13 Agustus 2014',
      address: 'PBC, Jl. Antilop Raya Pintu 11, Jababeka II Blok E-3 Kel. Jaya Mukti, Kec. Cikarang Pusat, Bekasi 17530 Jawa Barat – Indonesia',
      phone: '+62 21 2945 3728',
      email: 'cs@nikawa-indonesia.com',
    },
    vision: 'Menjadi penyedia solusi industri terkemuka dan terpercaya di Indonesia dengan menghadirkan inovasi dan keberlanjutan dalam komponen elektronik dan produk plastik.',
    mission: [
      {
        icon: 'quality',
        text: 'Menyediakan produk berkualitas tinggi yang memenuhi standar industri internasional',
      },
      {
        icon: 'partnership',
        text: 'Membangun kemitraan jangka panjang dengan pelanggan dan supplier melalui layanan profesional',
      },
      {
        icon: 'innovation',
        text: 'Mengembangkan inovasi teknologi yang mendukung efisiensi dan keberlanjutan di industri',
      },
      {
        icon: 'people',
        text: 'Mengembangkan SDM yang kompeten dan berintegritas sebagai fondasi pertumbuhan perusahaan',
      },
      {
        icon: 'contribution',
        text: 'Berkontribusi pada kemajuan industri nasional melalui solusi yang adaptif terhadap kebutuhan pasar',
      },
    ],
    businessFields: [
      { id: 'pcba', name: 'PCBA', image: '/images/products/pcba.jpg' },
      { id: 'led-road-stud', name: 'LED Road Studs', image: '/images/products/led-road-stud.jpg' },
      { id: 'plastic-resin', name: 'Plastic Resin', image: '/images/products/plastic-resin.jpg' },
      { id: 'gsm-modem', name: 'GSM Modem', image: '/images/products/gsm-modem.jpg' },
      { id: 'electronic-components', name: 'Electronic Components', image: '/images/products/electronic-components.jpg' },
      { id: 'plastic-injection', name: 'Plastic Injection Products', image: '/images/products/plastic-injection.jpg' },
      { id: 'smart-meters', name: 'Smart Meters', image: '/images/products/smart-water-meter.jpg' },
      { id: 'fiber-optic-gas-meters', name: 'Fiber Optic Gas Meters', image: '/images/products/fo-gas-meter.jpg' },
    ],
    strengths: [
      {
        title: 'Portofolio Produk yang Beragam',
        description: 'Menyediakan solusi lengkap di sektor elektronik dan plastik industri sesuai kebutuhan klien.',
        icon: 'portfolio',
      },
      {
        title: 'Lokasi Strategis di Jababeka Industrial Estate',
        description: 'Memudahkan distribusi dan logistik cepat ke seluruh Indonesia.',
        icon: 'location',
      },
      {
        title: 'Website Resmi & Struktur Organisasi Profesional',
        description: 'Transparansi informasi dan operasional yang jelas serta dapat dipercaya.',
        icon: 'professional',
      },
    ],
    brandIdentity: {
      logoMeaning: 'Logo NTI terdiri dari bentuk geometris inisial NTI dengan warna primer biru (#00719c) dan abu-abu (#808285), yang melambangkan inovasi, profesionalisme, dan stabilitas. Warna biru mencerminkan kepercayaan dan teknologi, sementara abu-abu menunjukkan soliditas dan profesionalisme.',
      colorSwatches: {
        primary: {
          hex: '#00719c',
          name: 'Biru - Inovasi & Kepercayaan',
        },
        secondary: {
          hex: '#808285',
          name: 'Abu-abu - Soliditas & Profesionalisme',
        },
      },
    },
    cta: {
      text: 'Kami siap menjadi mitra terpercaya Anda dalam memajukan industri Indonesia.',
      contact: 'Hubungi kami sekarang: cs@nikawa-indonesia.com | +62 21 2945 3728',
    },
  },
  brand: {
    colors: {
      primary: '#00719c',
      secondary: '#808285',
    },
    font: 'Gotham',
    characteristics: ['Prestisius', 'Elegan', 'Rapi', 'Organized'],
  },
}

